services:

  gateway-service:
    build:
      context: ./gateway
      dockerfile: ./gateway.dockerfile
    restart: always
    ports:
      - "8080:80"

  order-service:
    build:
      context: ./order
      dockerfile: ./order.dockerfile
    restart: always

  mongo:
    image: 'mongo:8.0.8-noble'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: orders
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db
