services:

  gateway-service:
    build:
      context: ./gateway
      dockerfile: ./gateway.dockerfile
    restart: always
    ports:
      - "8080:80"

  order-service:
    build:
      context: ./order
      dockerfile: ./order.dockerfile
    restart: always

  mongo:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: orders
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db
      
  rabbitmq:
    image: 'rabbitmq:4.1.0-alpine'
    ports:
      - "5672:5672"
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/